services:
  mongo:
    image: mongo:5.0
    ports:
      - 27018:27017

  minio:
    image: minio/minio
    ports:
      - 9001:9000
    environment:
      MINIO_ROOT_USER: test_minio_user
      MINIO_ROOT_PASSWORD: test_minio_password
    command: server /data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - minio-data:/data

volumes:
  minio-data: