name: Test storage service and build

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21 ]
    name: Run tests on Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify

  build:
    needs: [tests]
    runs-on: ubuntu-latest
    name: Build docker container
    steps:
      - uses: actions/checkout@v4
      - name: Docker build
      - run: docker build . -t storage-service:latest